server:
  port: 9998

spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:9999
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    httptrace:
      enabled: true